  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Categories"
  weight = 300
  identifier = "categories"
  url = "/categories/"

  [[main]]
  name = "Series"
  weight = 300
  identifier = "series"
  url = "/series/"

  [[main]]
  name = "About"
  weight = 100
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "Grow A Meal"
  weight = 500
  identifier = "grow"
  url = "/grow/"

  [[main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"

 [[footer]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[footer]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[footer]]
  name = "Categories"
  weight = 300
  identifier = "categories"
  url = "/categories/"

 [[footer]]
  name = "Tags"
  weight = 400
  identifier = "tags"
  url = "/tags/"

  [[footer]]
  name = "Series"
  weight = 500
  identifier = "series"
  url = "/series/"

  [[footer]]
  name = "About"
  weight = 600
  identifier = "about"
  url = "/about/"

  [[footer]]
  name = "Contact"
  weight = 700
  identifier = "contact"
  url = "/contact/"
